language: node_js
sudo: false
node_js:
  - "5"
env:
  global:
    - LODASH_VERSION="1.3.2"
  matrix:
    - 
    - LODASH_VERSION="2.4.2"
    - LODASH_VERSION="3.0.0"
matrix:
  include:
    - node_js: "0.10"
      env: 
    - node_js: "0.10"
      env: LODASH_VERSION="2.4.2"
    - node_js: "0.12"
      env: 
    - node_js: "0.12"
      env: LODASH_VERSION="2.4.2"
    - node_js: "4"
      env: 
    - node_js: "4"
      env: LODASH_VERSION="2.4.2"
git:
  depth: 10
branches:
  only:
    - master
before_install:
  - "nvm use $TRAVIS_NODE_VERSION"
  - "npm config set loglevel error"
  - "npm i -g npm@\"^2.0.0\""
  - "npm i lodash-cli@$LODASH_VERSION"
